[package]
name = "volt_core"
version = "0.0.1"
authors = ["Volt Contributors (https://github.com/voltpkg/volt/graphs/contributors)"]
description = "Volt's core library."
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
chttp = "0.5"
colored = "2.0"
console  = "0.14"
dialoguer = "0.8"
dirs = "3.0"
flate2 = "1.0"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha-1 = "0.9"
structopt = "0.3"
tar = "0.4"
thiserror = "1.0"
tokio = { version = "1.5.0", features = ["full"] }
utils = { path = "../utils" }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["errhandlingapi", "fileapi", "guiddef", "handleapi", "ioapiset", "processthreadsapi", "securitybaseapi", "winbase", "winioctl", "winnt"]}
tempfile = "3.2"
scopeguard = "1.1"
junction = { path = "../junction" }
